@startuml

title Diagrama de Clases - TP 2

abstract class Pedido {
    
    diaSemana: string
    items: Item[]

    + puedeFacturar(): boolean
    + estaElPedidoListo(): boolean
    + sacarDelPedido(item: Item): void
}

class PedidoSalon extends Pedido {
    
    esaAsociada: number

}

class PedidoRetirar extends Pedido {
    
    horarioRetiro: number

}

class PedidoEnvio extends Pedido {
    
    direccion: string
    costoEnvio: number

}

class itemPedido {
    
    estado: ESTADO_ITEM
}

interface Item {
    + getPrecioFinal(): number
    + estaListo(): boolean
    + sePuedeCancelar(): boolean
}

class Producto implements Item {
    
    nombre: string
    precio: number
    estacion: ESTACION
    estado: ESTADO_PEDIDO

    + abstract agregarPedido(): void
    + getPrecioFinal(): number
    + estaListo(): boolean
    + sePuedeCancelar(): boolean
}

class Combo implements Item {
    
    productos: Producto[]
    nombreCombo: string
    precioCombo: number
    porcentajeDescuento: number

    + getPrecioFinal(): number
    + estaListo(): boolean
    + sePuedeCancelar(): boolean
}


class Estacion {
    
    pedido: Pedido[]

    + preparPlato(p: Pedido): void

}


enum ESTADO_PEDIDO {
    EN_CONSTRUCCION,
    LISTO
}

enum ESTADO_ITEM {
    PENDIENTE,
    EN_PREPARACION,
    LISTO
}

enum CATEGORIA {
    ENTRADA,
    PRINCIPAL,
    BEBIDA,
    POSTRE
}

enum DIA_SEMANA {
    LUNES,
    MARTES,
    MIERCOLES,
    JUEVES,
    VIERNES,
    SABADO,
    DOMINGO
}