@startuml

title Diagrama de Clases - TP 2

class Restaurante {

    + crearCombo(): void
    + crearPedido(): void
}

abstract class Pedido {
    
    - diaSemana: string
    - items: Item[]

    + puedeFacturar(): boolean
    + sacarDelPedido(item: Item): void
    + agregarItem(item: Item): void
    + confirmar(): void 
}

class PedidoSalon extends Pedido {
    
    - MesaAsociada: number

}

class PedidoRetirar extends Pedido {
    
    - horarioRetiro: number

}

class PedidoEnvio extends Pedido {
    
    - direccion: string
    - costoEnvio: number

}

class itemPedido {
    
    - estado: ESTADO_ITEM
}

interface Item {
    + getPrecioFinal(): number
    + estaListo(): boolean
    + sePuedeCancelar(): boolean
}

class Producto implements Item {
    
    - nombre: string
    - precio: number
    - estacion: ESTACION
    - estado: ESTADO_


    + getPrecioFinal(): number
    + estaListo(): boolean
    + sePuedeCancelar(): boolean
}

class Combo implements Item {
    
    productos: Producto[]
    nombreCombo: string
    precioCombo: number
    porcentajeDescuento: number

    + getPrecioFinal(): number
    + estaListo(): boolean
    + sePuedeCancelar(): boolean
}


class Estacion {
    
    pedido: Pedido[]

    + preparPlato(p: Pedido): void

}


enum ESTADO_PEDIDO {
    EN_CONSTRUCCION,
    CONFIRMADO
}

enum ESTADO_ITEM {
    PENDIENTE,
    EN_PREPARACION,
    LISTO
}

enum ESTACION {
    ENTRADA,
    PRINCIPAL,
    BEBIDA,
    POSTRE
}

enum DIA_SEMANA {
    LUNES,
    MARTES,
    MIERCOLES,
    JUEVES,
    VIERNES,
    SABADO,
    DOMINGO
}